# Generated by Django 2.0.5 on 2018-07-25 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vennik', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='department',
            field=models.CharField(default='', max_length=100),
        ),
    ]
