# Generated by Django 2.0.5 on 2018-07-25 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vennik', '0002_userprofile_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LocationName', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
