# Generated by Django 2.0.5 on 2018-09-24 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vennik', '0004_auto_20180725_0902'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apartments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(default='', max_length=50)),
                ('price', models.IntegerField(default='0')),
                ('type', models.CharField(default='', max_length=50)),
                ('description', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
